export const USER_DETAILS = "USER_DETAILS";
export const PROFILE_DETAILS = "PROFILE_DETAILS";
export const CATEGORY_SUBCATE_SELECTION = "CATEGORY_SUBCATE_SELECTION";
export const SECTION_POST_A_JOB = "SECTION_POST_A_JOB";
export const CURRENT_USER_PROFILE = "CURRENT_USER_PROFILE";
export const CURRENT_USER_PROFILE_DETAILS = "CURRENT_USER_PROFILE_DETAILS";