export const USER_DETAILS = "USER_DETAILS";
export const PROFILE_DETAILS = "PROFILE_DETAILS";
export const CATEGORY_SUBCATE_SELECTION = "CATEGORY_SUBCATE_SELECTION";
export const SECTION_POST_A_JOB = "SECTION_POST_A_JOB";